import screenpy
import screenpy.actions
import screenpy.narration
import screenpy.narration.adapters
import screenpy.resolutions


def test_screenpy():
    expected = [
        "AbilityError",
        "act",
        "ActionError",
        "Actor",
        "Adapter",
        "AIRY",
        "AnActor",
        "and_",
        "Answerable",
        "aside",
        "Assert",
        "AssertAllOf",
        "AssertAnyOf",
        "AttachAFile",
        "AttachFile",
        "AttachTheFile",
        "BaseResolution",
        "beat",
        "Confirm",
        "ConfirmAllOf",
        "ConfirmAnyOf",
        "ContainItemMatching",
        "ContainsItemMatching",
        "ContainsTheEntries",
        "ContainsTheEntry",
        "ContainsTheItem",
        "ContainsTheKey",
        "ContainsTheText",
        "ContainsTheValue",
        "ContainTheEntries",
        "ContainTheEntry",
        "ContainTheItem",
        "ContainTheKey",
        "ContainTheText",
        "ContainTheValue",
        "Debug",
        "DeliveryError",
        "Describable",
        "Director",
        "DoesNot",
        "DoNot",
        "Empty",
        "EndsWith",
        "EndWith",
        "Equal",
        "Equals",
        "EqualTo",
        "ErrorKeeper",
        "Eventually",
        "EXTREME",
        "Forgettable",
        "given",
        "given_that",
        "GreaterThan",
        "GreaterThanOrEqualTo",
        "HasLength",
        "HEAVY",
        "InRange",
        "IsCloseTo",
        "IsEmpty",
        "IsEqual",
        "IsEqualTo",
        "IsGreaterThan",
        "IsGreaterThanOrEqualTo",
        "IsInRange",
        "IsLessThan",
        "IsLessThanOrEqualTo",
        "IsNot",
        "LessThan",
        "LessThanOrEqualTo",
        "LIGHT",
        "LoggingAdapter",
        "MakeNote",
        "Match",
        "Matches",
        "Narrator",
        "NORMAL",
        "noted",
        "noted_under",
        "Observe",
        "ObserveAllOf",
        "ObserveAnyOf",
        "Pause",
        "Performable",
        "QuestionError",
        "ReadExactly",
        "ReadsExactly",
        "scene",
        "ScreenPyError",
        "See",
        "SeeAllOf",
        "SeeAnyOf",
        "Sleep",
        "StartsWith",
        "StartWith",
        "StdOutAdapter",
        "TakeNote",
        "the_narrator",
        "the_noted",
        "then",
        "UnableToAct",
        "UnableToAnswer",
        "UnableToDirect",
        "UnableToNarrate",
        "UnableToPerform",
        "Verify",
        "VerifyAllOf",
        "VerifyAnyOf",
        "when",
    ]
    assert sorted(screenpy.__all__) == sorted(expected)


def test_actions():
    expected = [
        "Assert",
        "AssertAllOf",
        "AssertAnyOf",
        "AttachAFile",
        "AttachFile",
        "AttachTheFile",
        "Confirm",
        "ConfirmAllOf",
        "ConfirmAnyOf",
        "Debug",
        "Eventually",
        "MakeNote",
        "Observe",
        "ObserveAllOf",
        "ObserveAnyOf",
        "Pause",
        "See",
        "SeeAllOf",
        "SeeAnyOf",
        "Sleep",
        "TakeNote",
        "Verify",
        "VerifyAllOf",
        "VerifyAnyOf",
    ]
    assert sorted(screenpy.actions.__all__) == sorted(expected)


def test_resolutions():
    expected = [
        "BaseResolution",
        "ContainItemMatching",
        "ContainsItemMatching",
        "ContainsTheEntries",
        "ContainsTheEntry",
        "ContainsTheItem",
        "ContainsTheKey",
        "ContainsTheText",
        "ContainsTheValue",
        "ContainTheEntries",
        "ContainTheEntry",
        "ContainTheItem",
        "ContainTheKey",
        "ContainTheText",
        "ContainTheValue",
        "DoesNot",
        "DoNot",
        "Empty",
        "EndsWith",
        "EndWith",
        "Equal",
        "Equals",
        "EqualTo",
        "GreaterThan",
        "GreaterThanOrEqualTo",
        "HasLength",
        "InRange",
        "IsCloseTo",
        "IsEmpty",
        "IsEqual",
        "IsEqualTo",
        "IsGreaterThan",
        "IsGreaterThanOrEqualTo",
        "IsInRange",
        "IsLessThan",
        "IsLessThanOrEqualTo",
        "IsNot",
        "LessThan",
        "LessThanOrEqualTo",
        "Match",
        "Matches",
        "ReadExactly",
        "ReadsExactly",
        "StartsWith",
        "StartWith",
    ]
    assert sorted(screenpy.resolutions.__all__) == sorted(expected)


def test_narration():
    expected = [
        "AIRY",
        "EXTREME",
        "HEAVY",
        "LIGHT",
        "LoggingAdapter",
        "Narrator",
        "NORMAL",
        "StdOutAdapter",
    ]
    assert sorted(screenpy.narration.__all__) == sorted(expected)


def test_adapters():
    expected = [
        "LoggingAdapter",
        "StdOutAdapter",
    ]
    assert sorted(screenpy.narration.adapters.__all__) == sorted(expected)
