import screenpy
import screenpy.actions
import screenpy.resolutions
import screenpy.narration


def test_screenpy_namespace():
    expected = [
        "Actor",
        "AnActor",
        "Assert",
        "AssertAllOf",
        "AssertAnyOf",
        "AttachAFile",
        "AttachFile",
        "AttachTheFile",
        "Confirm",
        "ConfirmAllOf",
        "ConfirmAnyOf",
        "ContainItemMatching",
        "ContainTheEntries",
        "ContainTheEntry",
        "ContainTheItem",
        "ContainTheKey",
        "ContainTheText",
        "ContainTheValue",
        "ContainsItemMatching",
        "ContainsTheEntries",
        "ContainsTheEntry",
        "ContainsTheItem",
        "ContainsTheKey",
        "ContainsTheText",
        "ContainsTheValue",
        "Debug",
        "Director",
        "DoNot",
        "DoesNot",
        "Empty",
        "EndWith",
        "EndsWith",
        "Equal",
        "EqualTo",
        "Equals",
        "Eventually",
        "GreaterThan",
        "GreaterThanOrEqualTo",
        "HasLength",
        "InRange",
        "IsCloseTo",
        "IsEmpty",
        "IsEqual",
        "IsEqualTo",
        "IsGreaterThan",
        "IsGreaterThanOrEqualTo",
        "IsInRange",
        "IsLessThan",
        "IsLessThanOrEqualTo",
        "IsNot",
        "LessThan",
        "LessThanOrEqualTo",
        "MakeNote",
        "Match",
        "Matches",
        "Narrator",
        "Observe",
        "ObserveAllOf",
        "ObserveAnyOf",
        "Pause",
        "ReadExactly",
        "ReadsExactly",
        "See",
        "SeeAllOf",
        "SeeAnyOf",
        "Sleep",
        "StartWith",
        "StartsWith",
        "TakeNote",
        "Verify",
        "VerifyAllOf",
        "VerifyAnyOf",
        "act",
        "and_",
        "aside",
        "beat",
        "given",
        "given_that",
        "noted",
        "noted_under",
        "scene",
        "the_narrator",
        "the_noted",
        "then",
        "when",
    ]
    excluded = [
        "BaseResolution",
    ]
    assert sorted(screenpy.__all__) == sorted(expected)
    assert not any(item in excluded for item in screenpy.__all__)


def test_actions_namespace():
    expected = [
        "Assert",
        "AssertAllOf",
        "AssertAnyOf",
        "AttachAFile",
        "AttachFile",
        "AttachTheFile",
        "Confirm",
        "ConfirmAllOf",
        "ConfirmAnyOf",
        "Debug",
        "Eventually",
        "MakeNote",
        "Observe",
        "ObserveAllOf",
        "ObserveAnyOf",
        "Pause",
        "See",
        "SeeAllOf",
        "SeeAnyOf",
        "Sleep",
        "TakeNote",
        "Verify",
        "VerifyAllOf",
        "VerifyAnyOf",
    ]
    excluded = []
    assert sorted(screenpy.actions.__all__) == sorted(expected)
    assert not any(item in excluded for item in screenpy.actions.__all__)


def test_resolutions_namespace():
    expected = [
        "BaseResolution",
        "ContainItemMatching",
        "ContainsItemMatching",
        "ContainsTheEntries",
        "ContainsTheEntry",
        "ContainsTheItem",
        "ContainsTheKey",
        "ContainsTheText",
        "ContainsTheValue",
        "ContainTheEntries",
        "ContainTheEntry",
        "ContainTheItem",
        "ContainTheKey",
        "ContainTheText",
        "ContainTheValue",
        "DoesNot",
        "DoNot",
        "Empty",
        "EndsWith",
        "EndWith",
        "Equal",
        "Equals",
        "EqualTo",
        "GreaterThan",
        "GreaterThanOrEqualTo",
        "HasLength",
        "InRange",
        "IsCloseTo",
        "IsEmpty",
        "IsEqual",
        "IsEqualTo",
        "IsGreaterThan",
        "IsGreaterThanOrEqualTo",
        "IsInRange",
        "IsLessThan",
        "IsLessThanOrEqualTo",
        "IsNot",
        "LessThan",
        "LessThanOrEqualTo",
        "Match",
        "Matches",
        "ReadExactly",
        "ReadsExactly",
        "StartsWith",
        "StartWith",
    ]
    excluded = []
    assert sorted(screenpy.resolutions.__all__) == sorted(expected)
    assert not any(item in excluded for item in screenpy.resolutions.__all__)
